version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3000"
    environment:
      - DEV_TO_API_KEY=${DEV_TO_API_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=3000