version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEV_TO_API_KEY=${DEV_TO_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET_KEY=${GITHUB_SECRET_KEY}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - PORT=3000