name: Deploy to VPS

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    environment: 
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t samluiz/blog:latest .
          docker push samluiz/blog:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_SSH_IP }}
          username: ${{ secrets.ORACLE_SSH_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop blog
            sudo docker rm blog
            sudo docker pull samluiz/blog:latest
            cd blog
            sudo docker run -d -t -i -e ADMIN_NAME -e ADMIN_PASSWORD -e ADMIN_USERNAME -e DATABASE_URL -e DEV_TO_API_KEY -e GITHUB_CLIENT_ID -e GITHUB_REDIRECT_URI -e GITHUB_SECRET_KEY -e PORT -e TURSO_AUTH_TOKEN --name blog samluiz/blog:latest
