name: Keep alive cron job
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the app alive
        run: |
          curl --request GET \
            --url 'https://blog.samluiz.com'
