name: Purge Cloudflare Cache

on:
  push:
    branches: [ main ]

jobs:
  curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Purge cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache"
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}"
          -H "Content-Type: application/json"
          --data '{"purge_everything": true}'
